# Generated by Django 2.2.5 on 2019-09-25 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_todoitem_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoitem',
            name='item',
            field=models.CharField(max_length=15),
        ),
    ]
