# Generated by Django 2.2.5 on 2019-09-25 08:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_auto_20190925_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoitem',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 25, 14, 5, 37, 10896)),
        ),
    ]
